name: Build and Release Application

on:
  push:
    branches:
      - build

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: List build artifacts
        run: ls -l ./build/libs

      # Rename the JAR if needed. This assumes only one JAR is produced.
      - name: Rename JAR
        run: mv ./build/libs/*.jar ./build/libs/application.jar

      # Create a release for 'build-only' tag
      - name: Create Release (build-only)
        uses: actions/create-release@v1
        with:
          tag_name: build-only
          release_name: "Build Only Release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload build artifact to the 'build-only' release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/libs/application.jar
          asset_name: application.jar
          tag: 'build-only'
          overwrite: true
          body: "Build artifact for application"

      # Create a release for 'publish-only' tag
      - name: Create Release (publish-only)
        uses: actions/create-release@v1
        with:
          tag_name: publish-only
          release_name: "Publish Only Release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload publish artifact to the 'publish-only' release
      - name: Upload publish artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./publish/output.zip
          asset_name: output.zip
          tag: 'publish-only'
          overwrite: true
          body: "Publish output artifact for application"
